# Generated by Django 5.0.6 on 2024-06-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha Salida')),
                ('salario', models.IntegerField(verbose_name='Salario')),
                ('tipo_contrato', models.CharField(choices=[('CF', 'Contrato de trabajo fijo'), ('CT', 'Contrato temporal'), ('CO', 'Contrato por obra'), ('CI', 'Contrato de trabajo indefinido'), ('CA', 'Contrato de aprendizaje')], max_length=3, verbose_name='Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.IntegerField(verbose_name='Descuento')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('fecha_inicio_promo', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin_promo', models.DateField(verbose_name='Fecha Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nick', models.CharField(max_length=16, unique=True, verbose_name='Nombre usuario')),
                ('nombre', models.CharField(max_length=16, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=16, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='correo')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('numero_casa_departamento', models.IntegerField(verbose_name='Numero de Casa')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Tienda')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha Creacion')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empleado', verbose_name='ID empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('categoria_producto', models.CharField(choices=[('F', 'Figuras'), ('P', 'Pinturas'), ('A', 'Accesorios')], max_length=2, verbose_name='Categoria')),
                ('foto', models.ImageField(null=True, upload_to='personas')),
                ('fk_promocion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.promocion', verbose_name='ID Promocion')),
                ('fk_tienda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.tienda', verbose_name='ID Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('fecha_boleta', models.DateField(verbose_name='Fecha')),
                ('giro', models.CharField(choices=[('GC', 'Giro Comercial Mayorista')], max_length=3, verbose_name='Giro')),
                ('medio_pago', models.CharField(choices=[('TB', 'Transferencia Bancaria'), ('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta de Débito')], max_length=3, verbose_name='Medio Pago')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.producto', verbose_name='ID Producto')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.usuario', verbose_name='ID Usuario')),
            ],
        ),
    ]
