# Generated by Django 5.0.6 on 2024-06-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuario',
            name='aplicacion__nick_417b84_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nick',
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rut'], name='aplicacion__rut_97106f_idx'),
        ),
    ]
