# Generated by Django 5.0.6 on 2024-06-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='aplicacion__rut_97106f_idx',
        ),
    ]
