# Generated by Django 5.0.6 on 2024-06-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='perfil',
            name='aplicacion__usuario_89099e_idx',
        ),
    ]
