# Generated by Django 5.0.6 on 2024-06-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='fk_usuario',
        ),
    ]
