# Generated by Django 5.0.6 on 2024-06-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_customuser_remove_perfil_usuario_delete_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
