# Generated by Django 5.0.6 on 2024-06-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fk_promocion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fk_tienda',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
