# Generated by Django 5.0.6 on 2024-07-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='', max_length=9, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
