# Generated by Django 5.0.6 on 2024-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.CharField(choices=[('1', 'Miniaturas'), ('2', 'Pinturas'), ('3', 'Accesorios')], max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Foto'),
        ),
    ]
