# Generated by Django 5.0.6 on 2024-07-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_remove_perfil_rut_carrito_itemcarrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
