# Generated by Django 5.0.6 on 2024-07-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='aplicacion.boleta')),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='aplicacion.carrito')),
            ],
        ),
    ]
