# Generated by Django 5.0.6 on 2024-07-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(related_name='carritos', through='aplicacion.ItemCarrito', to='aplicacion.producto'),
        ),
    ]
