# Generated by Django 5.0.6 on 2024-07-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_alter_producto_descripcion'),
        ('aplicacion', '0022_perfil'),
    ]

    operations = [
    ]
