# Generated by Django 5.0.6 on 2024-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_alter_producto_categoria_producto'),
        ('aplicacion', '0022_perfil'),
    ]

    operations = [
    ]
