# Generated by Django 5.0.6 on 2024-07-05 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0023_merge_20240705_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
