# Generated by Django 5.0.6 on 2024-07-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0024_alter_producto_descripcion_compra'),
    ]
    operations = [
    ]
