# Generated by Django 5.0.6 on 2024-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0025_auto_20240705_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
    ]
