# Generated by Django 5.0.6 on 2024-07-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0026_alter_producto_descripcion'),
    ]

    operations = [
    ]
