# Generated by Django 5.0.6 on 2024-07-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0027_alter_producto_descripcion'),
        ('aplicacion', '0027_auto_20240705_0358'),
    ]

    operations = [
    ]
