# Generated by Django 5.0.6 on 2024-07-08 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0029_remove_compra_carrito_compra_total_compra_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible'),
        ),
    ]
