# Generated by Django 5.0.6 on 2024-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0032_producto_stock_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado_entrega',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('R', 'Recibido'), ('X', 'Cancelado')], default='P', max_length=1),
        ),
    ]
