# Generated by Django 5.0.6 on 2024-07-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0034_alter_itemcarrito_cantidad'),
    ]

    operations = [
    ]
