# Generated by Django 5.0.6 on 2024-07-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0033_alter_compra_estado_entrega'),
        ('aplicacion', '0037_alter_compra_estado_entrega'),
    ]

    operations = [
    ]
